### PR TITLE
fixed a few things in main readme file too :3

### PR DESCRIPTION
**Pull request by AushevAhmad**
meow meow :3

### CODE REVIEW

**Comment by AushevAhmad** [comment]
also wait

**Comment by khcrysalis** [comment]
My typos are awesome sometimes

**Comment by AushevAhmad** [comment]
Don't merge yet

**Comment by AushevAhmad** [comment]
> My typos are awesome sometimes

lmao

**Comment by AushevAhmad** [comment]
uhh, ok so, now you can merge :3

**Pull request merged**
