### PR TITLE
German localization and german README

### PR DESCRIPTION
**Pull request by t0mi**

### CODE REVIEW

**Review by khcrysalis — APPROVED** [review]
lgtm

**Comment by khcrysalis** [comment]
Yet, make the changes I requested and I'll squash and merge.

**Comment by t0mi** [comment]
Hey, I would like to make the changes you requested to, but unfortunately I can’t find any comments or anything like that with what you want to have changed.

**Comment by khcrysalis** [comment]
> Hey, I would like to make the changes you requested to, but unfortunately I can’t find any comments or anything like that with what you want to have changed.

image

Ive made a comment here with the line youve changed.

**Comment by t0mi** [comment]
Done :)

**Pull request merged**
