### PR TITLE
Fix grammar mistake in README.md

### PR DESCRIPTION
**Pull request by avifcollective**
Screenshot_20241204-073908

### CODE REVIEW

**Comment by khcrysalis** [comment]
"Merging is blocked"

**Comment by RayJW** [comment]
I'm sorry to be that guy, but that's not even a fix. “An” is correct in this case, as HTTPS is an acronym starting with a vowel sound, e.g. an MRI [em-arr-eye]. So to actually use proper grammar, this should be reverted. Feel free to check whatever trusted source you have to double-check this.

**Comment by castdrian** [comment]
yep this was correct as it was

**Comment by khcrysalis** [comment]
What's most funny about this is that the british pronunciation of HTTPS makes "a" more appropriate, there was a whole argument elsewhere where this all started and there was a mix between the two

**Comment by castdrian** [comment]
I'd like a word with whoever misprounounced [eytsch] kek

**Comment by khcrysalis** [comment]
(as the british people call it)

**Comment by avifcollective** [comment]
> I'd like a word with whoever misprounounced [eytsch] kek

Wsg man, you got a problem with it?? 👹👹🧨🧨🔥🔥

**Pull request merged**
