### PR TITLE
Add Dutch Translations

### PR DESCRIPTION
**Pull request by SerStars**
"lame"

### CODE REVIEW

**Comment by SerStars** [comment]
im out of commit names 💀

**Comment by SerStars** [comment]
@khcrysalis bump

**Comment by khcrysalis** [comment]
Could you review your changes again to make sure they currently align with the current readme?

**Comment by SerStars** [comment]
Don't really see a point to add Dutch Translations and I don't have the time work on this.
If @Dosojin1 would like to continue, they can continue on their [PR #49](https://github.com/khcrysalis/Feather/pull/49)

I would've continued but it's a bit too much work for me.

**Pull request closed without merging**
