### PR TITLE
small improvements idk

### PR DESCRIPTION
**Pull request by AushevAhmad**
updated russian and english README files(🤓) and improved a russian localization file a lil bit :3

### CODE REVIEW

**Comment by AushevAhmad** [comment]
samara rn: I pushed updates 5 hours ago and this mf is already here, you have no life

**Review by MuzahidGithub — COMMENTED** [review]
looks good to me

**Comment by khcrysalis** [comment]
Could you review your changes again to make sure they currently align with the current readme?

**Comment by AushevAhmad** [comment]
I've updated the readme files and for both english and russian readme i added `> [!WARNING]` thingies on 67th line cuz idk.. it looks better imo instead of a just `*NOTE*` or whatever :P

**Review by khcrysalis — APPROVED** [review]
lgtm

**Pull request merged**
