### PR TITLE
feat: app updates

### LINKED ISSUE #166: Handle Updates
Can we possibly get a feature in the future that will show if the apps we have signed/installed have an update available including the Feather App itself? Also I would like to be able to update the Feather App within itself. Currently it crashes and says it was unable to install the Feather app when I try to install the new updated version. Thanks

### PR DESCRIPTION
**Pull request by castdrian**
this aims to close #166 by implementing update checking, prompting, notifying and performing the install flow
this is probably extremely messy, I apologise, frankly the codebase was way bigger than I expected and I've just kinda been waddling through an ocean blindfolded

screenshot

### CODE REVIEW

**Comment by khcrysalis** [comment]
Is there a reason why almost the entire project has been formatted?

**Comment by castdrian** [comment]
Oh yeah I have an automation that runs swiftformat and commits it in every Xcode project, I can revert that though if you're not a fan of swiftformat, I'm more concerned with how bad my implementation is, first time I've encountered CoreData rather than a UserDefaults lib, I've only done swift for a couple years so this is probably not A grade quality 🥲

**Comment by khcrysalis** [comment]
So after reviewing some of, I'm gonna point out things that I've noticed

- You've changed some of the design of the cells, which upon doing that removed the ability to see the source where the app has been imported. (Also making a seperate bundleid field makes the cells unnecessarily big)

- You have also removed the ability to open the app within the sheet that appears when pressing on a cell, including the functionality to resign an app optionally with a different certificate.

- While the updating functionality is pretty cool in my opinion, it shouldn't really consider if an app is installed because it's hard to tell if it actually *is*. For example, pressing install on a signed app may not install either by lack of entitlements, ssl cert expiring, dev cert expiring, and not being able to install with online method due to no hotspot.

- Theres also a bug where it may crash upon launch due to presumably updating stuff on the incorrect thread, from my experience at least as it needed a few launches before it actually was successful.

**Comment by castdrian** [comment]
ah fuck me, I'll see to restoring all of that to how it was and fix the threading

**Comment by castdrian** [comment]
I believe I've addressed everything and provided a way cleaner approach this time, by nuking the branch back to main and then cherry picking the update functionality back into the signed apps cells instead and adjusting it to not just randomly break everything 
https://github.com/user-attachments/assets/e7452028-ff6e-4bf4-bd6b-470996631ba1

**Review by Rafter9875 — APPROVED** [review]

**Comment by khcrysalis** [comment]
I haven't gotten able to get app updates working outside of the mock sources, is there a reason for that?

**Comment by castdrian** [comment]
> I haven't gotten able to get app updates working outside of the mock sources, is there a reason for that?

did you run in release configuration or in debug configuration? if your scheme is set to debug it will always choose the mock source

**Comment by khcrysalis** [comment]
It's not choosing the mock source when it's using release mode so that's good, but it doesn't seem any different from what it was. When choosing debug the mock source works fine, and actually shows that it works to an extent but doesn't show the same in release.

**Comment by khcrysalis** [comment]
image

**Comment by castdrian** [comment]
very funny thing there, apparently I was checking agains the top level `version` field in release mode instead of iterating through the `versions` array, why do the altstore people have to define two similar keys ㅠㅠ

**Comment by khcrysalis** [comment]
People have two versions keys mainly for compatibility with older altstore versions and other apps that use the scheme

**Comment by khcrysalis** [comment]
The version array should be first priority as altstore uses that in their 2.0 scheme

**Comment by castdrian** [comment]
this worked in both release and debug config, tested the same way you did with just feather itelf, download 1.1.2 relaunched, update prompt

**Comment by castdrian** [comment]
i pinky promise, I tested every step on both scheme configurations now it actually does fully accomplish the update flow

**Comment by khcrysalis** [comment]
"merging is blocked" nuh uh

**Pull request merged**
