### PR TITLE
Make AppIcon to works for Dark & Tinted mode on iOS 18

### PR DESCRIPTION
**Pull request by brynts**
Add Dark icon & Tinted icon for iOS 18, also adding code to AppDelegate code, to make AppIcon working in Welcome Screen

### CODE REVIEW

**Comment by khcrysalis** [comment]
If I ever merge this PR, there's gonna be two options before hand that needs to be decided.
- Have the feather default icon as one of your icons, because compiling with Xcode 15.0.1 will prioritize the first icon in the directory and choose that as it's icon.
- Upgrade to Xcode 16 (may cause problems for development)

**Comment by khcrysalis** [comment]
Last time I compiled with Xcode 16, it made feather crash on launch which isn't something that should be happening.

**Comment by brynts** [comment]
If you only adding icons to iOS 18's format, Feather will crash in launch, because Feather's welcome screen needs call initial AppIcon, so that why I added `UIOnboardingHelper` to call initial AppIcon for setupIcon

IDK, I can run without crash with my PR in my Xcode 16, I hope you can implement this..

**Comment by brynts** [comment]
oh, I thought you won't, maybe you can send me Feather's icon EPS/PSD/anything, I'll help you make the proper icons needs with the shadow

**Comment by khcrysalis** [comment]
Thats really not the issue. Read my messages above.

**Comment by brynts** [comment]
original icon (purple) not loaded on my phone, but it's loaded in simulator, lmao.. idk how

**Pull request closed without merging**
